bookappjsf:
  image: bookapp_jsf:latest
  ports:
   - "9991:8080"
  links:
   - bookapprest

bookapprest:
  image: bookapp_rest:latest
  ports:
   - "9992:8080"

hub:
  image: selenium/hub:latest
  ports:
    - "4445:4444"
firefox:
  image: selenium/node-firefox:latest
  links:
    - hub
chrome:
  image: selenium/node-chrome:latest
  links:
    - hub    
